[book]
authors = ["Occidental Autores"]
language = "ie"
multilingual = false
src = "src"
title = "scritorium"

[output.html]
theme = "src/theme"
default-theme = "rust"
git-repository-url = "https://github.com/occidental-lang/scritorium"
site-url = "/scritorium/"

[output.html.fold]
enable = true
level = 0

[build]
build-dir = "docs"
